### ISSUE TITLE
How do i make the app understand other languages?

### ISSUE THREAD

**Issue by CasanovaSan** [ILikeAI/AlwaysReddy#69]
I am having a issue that when i speak with it, it doesn't understand me (i speak romanian) and i was wondering if there is a way to change the language that it can understand into romanian

**Comment by Jobus0** [comment]
Are you using FasterWhisper to transcribe locally? If so, then take a look at the `WHISPER_MODEL` option in config.py — is it set to the default of `tiny.en`? The `.en` suffix means that it is a special english-only model. Simply change it to `WHISPER_MODEL = "tiny"` and it will download the multilingual model instead.

Note that Whisper is less accurate with some languages compared to others. However, you can improve that by using larger models instead of `tiny`.

These are all the available multilingual models, from smallest to largest:
`tiny`, `base`, `small`, `medium`, `large`

However, larger models will also run slower. If you have a dedicated GPU, try setting `USE_GPU = True` in config.py as well, which will make FasterWhisper run the larger models much faster than with the CPU.
